/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://zkduh552jfhe7gix4gsjngbuzu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-64krlii6wnep5ktz3wjjifwnje",
    "aws_cognito_identity_pool_id": "us-east-2:2456d2b0-5ab6-476d-b62a-bc9513e08a3a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0m8GbVfSR",
    "aws_user_pools_web_client_id": "331vhnebeo64llvffm0iq64325",
    "oauth": {
        "domain": "6xw1mj6xycui-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d1hjlbt9fxfen0.amplifyapp.com",
        "redirectSignOut": "https://main.d1hjlbt9fxfen0.amplifyapp.com",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "myxp-storage185100-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
